### ISSUE TITLE
List of supported file systems?

### ISSUE THREAD

**Issue by hinell** [i-rinat/fragview#10]

**Comment by i-rinat** [comment]
It should work with filesystems that support FIEMAP ioctl. That include ext4 and btrfs. Maybe others, I'm not sure. If filesystem support FIEMAP ioctl, fragview should be able to get file and directory layout information with ordinary user rights.
There is a fall-back code path that will try to use FIBMAP ioctl. It's available on more filesystems, but requires root rights, and only supports mapping files, but not directories.

**Comment by hinell** [comment]
Didn't knwot that it proxies requests via System Call. Thank you.
