### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by Flowdalic** [i-rinat/fragview#11]
It's been a while since 0.1.1 was tagged, there have some minor changes and after that the project seems to stand still (which is, of course, fine). But maybe consider tagging the latest HEAD as 0.2.0 or so.

**Comment by i-rinat** [comment]
Pushed a new tag: https://github.com/i-rinat/fragview/releases/tag/v0.1.2.

**Comment by Flowdalic** [comment]
Thanks, I've added fragview 0.1.2 to ::gentoo.
